### ISSUE TITLE
when will you release the data and code

### ISSUE THREAD

**Issue by ZihaoZheng98** [HarryWgCN/SGCAT-CT#1]

**Comment by HarryWgCN** [comment]
Thanks for your enquiry! The data used in this framework includes MovieGraphs, ViSR, HLVU and LVU. Due to copyright issues, we cannot provide you with the data directly. We suggest you locating its original paper and contact the authors. Apology for the wait and the code of this framework will be gradually released within a month. Note: the source code will be released to 'master' branch instead of 'main' branch.

**Comment by HarryWgCN** [comment]
Most parts of the code has been uploaded. Thank you for your patience!
